language: node_js
sudo: true
dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - xsel
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
